config/routes.rb
Rails.application.routes.draw do
  # Moved mounts up to make sure they run before everything. R.
  mount Attachinary::Engine => "/attachinary"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :mother_listings do
    resources :bookings, only: [:show, :new, :create, :destroy]
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  resources :users, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mother_listing.rb
class MotherListing < ApplicationRecord
  belongs_to :user
  belongs_to :user_favorite
  has_many :bookings
  belongs_to :user_review
  has_many :mother_listing_reviews
  has_one :mother_skill
  has_many :skills, through: :mother_skill

  def validate_availability
      errors.add("Availability ") if self.availability_from >= self.availability_to
  end

  def self.search(search)
    # where("first_name LIKE ?", "%#{search}%")
    # where("last_name LIKE ?", "%#{search}%")
    where("description LIKE ?", "%#{search}%")
    # this will work in development with SQLite. If you switch to PostgreSQL in production
    # you may need to change  LIKE to  ILIKE
  end

  has_attachment :photo
end

app/controllers/mother_listings_controller.rb
class MotherListingsController < ApplicationController
  before_action :set_mother_listing, only: [:show, :edit, :update, :destroy]

  def index
    @mother_listings = MotherListing.all
    # Simple search as per http://www.korenlc.com/creating-a-simple-search-in-rails-4/
    if params[:search]
      @mother_listings = MotherListing.search(params[:search]).order("created_at DESC")
    else
      @mother_listings = MotherLisitng.all.order('created_at DESC')
    end

    if current_user
      @mother_listings = MotherListing.not_belonging_to_current_user(current_user.id)
    else
      @mother_listings = MotherListing.all
    end
  end

  def show
    @booking =  ActsAsBookable::Booking.new
  end

  def new
    @mother_listings = MotherListing.new
  end

  def create
    @mother_listing = MotherListing.new(mother_listing_params)
    if @mother_listing.save
      redirect_to mother_listing_path(@mother_listing)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @mother_listing.update(mother_listing_params)
    redirect_to mother_listings_path(@mother_listing)
  end

  def destroy
    @mother_listing = MotherListing.find(params[:id])
    @mother_listing.destroy
    redirect_to mother_listings_path
  end

  private

  def set_mother_listing
    @mother_listing = MotherListing.find(params[:id])
  end


  def mother_listing_params
    params.require(:mother_listing).permit(:id, :first_name, :last_name, :price, :location, :description, :photo)
  end

end

app/helpers/mother_listings_helper.rb
module MotherListingsHelper
end

app/views/mother_listings/index.html.erb
<% if @mother_listings.present? %>
  <ul>
  <% @mother_listings.each do |result| %>
  <li><%= result.description %></li>
  <% end %>
  </ul>
<% else %>
  <p>We could not find any moms containing the term(s) <%= params[:search] %>. Try again with other keywords!</p>
<% end %>

app/views/mother_listings/new.html.erb
<%= simple_form_for @mother_listing do |f| %>

<%= f.input :photo, as: :attachinary %>

<%= f.input :first_name, placeholder: 'Fist Name' %>

<%= f.input :last_name, placeholder: 'Last Name' %>

<%= f.input :description, placeholder: 'Description' %>

<%= f.button :submit %>
<% end %>

app/views/mother_listings/show.html.erb
<div class="page-content" style="margin-top: 50px; margin-bottom: 50px;">
  <div class="mdl-grid">

    <div class="mdl-cell mdl-cell--4-col"></div>
    <div class="mdl-cell mdl-cell--4-col">

        <%= form_for [@mother_listing, @booking], url: mother_listing_bookings_path(@mother_listing) do |f| %>
        <div class="demo-card-wide mdl-card mdl-shadow--2dp EditNewCard">
          <h1>About this Mum</h1>

          <%= image_tag "mom1.jpg", width: 200, height: 200, :class => "circle-img" %>

          <h1><%= "#{@mother_listing.first_name} #{@mother_listing.last_name}" %></h1>

          <p><%= @mother_listing.description %></p>
          <div class="mdl-card__actions mdl-card--border">
          <% if user_signed_in? %>
            <%= link_to 'Edit', edit_mother_listing_path(@mother_listing), :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
            <%= link_to 'Book', new_mother_listing_booking_path(@mother_listing), :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
          <% else %>
            <%= link_to 'Book', new_mother_listing_booking_path(@mother_listing), :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
          <% end %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>
</div>