config/routes.rb
Rails.application.routes.draw do
  # Moved mounts up to make sure they run before everything. R.
  mount Attachinary::Engine => "/attachinary"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :mother_listings do
    resources :bookings, only: [:show, :new, :create, :destroy]
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  resources :users, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :mother_listing

#Validations
validates_presence_of :guests_count
validate :booking_period_validation

def self.validate_and_create(params, current_user)
  booking = current_user.bookings.new(params[:booking])
  mother_listing = MotherListing.find(params[:booking][:mother_listing_id])
  if Date.today > mother_listing.availability_from && Date.today > mother_listing.availability_to
    message = "The listing's availability has expired"
    path = reserve_mother_listing_path params[:booking][:mother_listing_id]
  elsif mother_listing.availability_from > booking.check_in || mother_listing.availability_to < booking.check_out
    message = "You can reserve this listing only for the period #{mother_listing.availability_from} - #{mother_listing.availability_to}"
    path = reserve_mother_listing_path params[:booking][:mother_listing_id]
  else
    if booking.save
      message = "booking was successfully created."
      path = booking
    else
      message = booking.errors.full_messages.to_sentence
      path = reserve_mother_listing_path params[:booking][:mother_listing_id]
    end
  end
  result = {
    :message => message,
    :path => path
  }
  return result
end

def self.validate_and_destroy(booking)
  mother_listing = MotherListing.find(booking.mother_listing_id)
  if Date.today < booking.check_in + mother_listing.notice_period
    booking.destroy
    message = "successfully cancelled the booking!"
    path = bookings_path
  else
    message = "You cannot cancel the booking. Minimum notice period is #{mother_listing.notice_period} days"
    path = (booking)
  end
  result = {
    :message => message,
    :path => path
  }
  return result
end

def self.validate_and_update(params, booking)
  if booking.update_attributes(params[:booking])
   message = "booking was successfully updated."
   path = booking
 else
  message = booking.errors.full_messages.to_sentence
  path = {:action => "edit"}
end
result = {
  :message => message,
  :path => path
}
end

private
  def booking_period_validation
    errors.add("booking period ") if self.check_in >= self.check_out
  end
end

app/models/mother_listing.rb
class MotherListing < ApplicationRecord
  belongs_to :user
  belongs_to :user_favorite
  has_many :bookings
  belongs_to :user_review
  has_many :mother_listing_reviews
  has_one :mother_skill
  has_many :skills, through: :mother_skill

  def validate_availability
      errors.add("Availability ") if self.availability_from >= self.availability_to
  end

  def self.search(search)
    # where("first_name LIKE ?", "%#{search}%")
    # where("last_name LIKE ?", "%#{search}%")
    where("description LIKE ?", "%#{search}%")
    # this will work in development with SQLite. If you switch to PostgreSQL in production
    # you may need to change  LIKE to  ILIKE
  end

  has_attachment :photo
end

app/models/mother_listing_review.rb
class MotherListingReview < ApplicationRecord
  belongs_to :user
  belongs_to :mother_listing
end

app/models/mother_skill.rb
class MotherSkill < ApplicationRecord
  has_many :skills
  belongs_to :mother_listing
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :mother_skill
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_reviews
  has_many :user_favorites
  has_many :bookings
  has_many :mother_listings # Could be renting out one or more moms
  has_many :mother_listing_reviews
  # Shortcut to be able to refference mother_listing directly without going through booking
  has_many :book_moms, through: :bookings, :source => :mother_listing
  # Shortcut to be able to refference mother_listing directly without going through user_favorite
  has_many :favorite_moms, through: :user_favorites, :source => :mother_listing

  has_attachment :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_booker
end

app/models/user_favorite.rb
class UserFavorite < ApplicationRecord
  belongs_to :user
  has_many :mother_listings
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :mother_listing
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking_params, :only => [:show, :edit, :update, :destroy]

  def index
    @title = "My reservations"
    @bookings = current_user.bookings
  end

  def new

  end

  def show

  end

  def edit

  end

  def create
    # @booking = Booking.new(set_booking_params)
    @mother_listing = MotherListing.find(params[:mother_listing_id])
    # starting_time = Date.parse(params[:acts_as_bookable_booking][:time_start])
    # ending_time = Date.parse(params[:acts_as_bookable_booking][:time_end])
    # current_user.book! @mother_listing, time_start: starting_time, time_end: ending_time
    current_user.book! @mother_listing
    redirect_to user_path(current_user)
    # if @booking.save
    #   redirect_to booking_path(@booking)
    # else
    #   render :new
    # end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_booking_params
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/user_reviews_controller.rb
class UserReviewsController < ApplicationController

 def new
    @user_review = UserReview.new
  end

  def create
    @user_review = UserReview.new(user_review_params)
    if @user_review.save
      redirect_to user_review_path(@user_review)
    else
      render :new
    end
  end

  private

  def user_review_params
    params.require(:user_review).permit(:id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(user_params)
  end

private
  # Doc requires this but where do we use it?
  def user_params
    params.require(:user).permit(:first_name, :last_name, :average_rating, :description, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/mother_listings_helper.rb
module MotherListingsHelper
end

app/helpers/user_favorites_helper.rb
module UserFavoritesHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forms/_homesearch.html.erb
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form_tag(mother_listings_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Find a mom", :class => "mdl-textfield__input" %>
      <%= submit_tag "Search", :class => "mdl-textfield__button" %>
    <% end %>
  </div>

app/views/layouts/_footer.html.erb
<footer class="mdl-mega-footer">
  <div class="mdl-mega-footer__middle-section">

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Features</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">About</a></li>
        <li><a href="#">Terms</a></li>
        <li><a href="#">Partners</a></li>
        <li><a href="#">Updates</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Details</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">Specs</a></li>
        <li><a href="#">Tools</a></li>
        <li><a href="#">Resources</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Technology</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">How it works</a></li>
        <li><a href="#">Patterns</a></li>
        <li><a href="#">Usage</a></li>
        <li><a href="#">Products</a></li>
        <li><a href="#">Contracts</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">FAQ</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">Questions</a></li>
        <li><a href="#">Answers</a></li>
        <li><a href="#">Contact us</a></li>
      </ul>
    </div>

  </div>

  <div class="mdl-mega-footer__bottom-section">
    <%= image_tag "rta_logo.png", class: "img-circle", height: 30, width: 40 %>
        <ul class="mdl-mega-footer__link-list">
      <li><a href="#">Help</a></li>
      <li><a href="#">Privacy & Terms</a></li>
    </ul>
  </div>

</footer>

app/views/layouts/_nav.html.erb
<header class="mdl-layout__header nav-down">
  <div class="mdl-layout__header-row">
  <%= link_to root_path do %>
    <span class="mdl-layout-title">
    <%= image_tag "rta_logo.png",height: 60 %></span>
  <% end %>
    <div class="mdl-layout-spacer"></div>
    <nav class="mdl-navigation">

    <% if user_signed_in? %>

      <%= link_to "Profile", edit_user_registration_path, :class => "mdl-navigation__link" %>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "mdl-navigation__link" %>

    <% else %>

      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, :class => "mdl-navigation__link" %>
      <%= link_to t(".sign_in", default: "Sign In"), new_user_session_path, :class => "mdl-navigation__link" %>

    <% end %>

    </nav>
  </div>
</header>
<div class="mdl-layout__drawer mdl-layout--small-screen-only">
  <span class="mdl-layout-title">Menu</span>
  <nav class="mdl-navigation">
    <a class="mdl-navigation__link" href="#">Links</a>
    <a class="mdl-navigation__link" href="#">Links</a>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Rentamum</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <div class="mdl-layout__header mdl-layout__header--waterfall">

        <%= render 'layouts/nav' %>

      </div>

      <%= yield %>

      <% if current_page?(root_path) %>
        <%= render 'layouts/footer' %>
      <% end %>

    </div>

    <%= cloudinary_js_config %>

    <%= javascript_include_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner mdl-typography--text-center">
  <div class="vertical-align-middle padding-bottom-3" style="height: 100%">
    <h1>Rent A Mum</h1>
    <h2>For times when you're tired of your mum.</h2>

    <%= render 'forms/homesearch' %>

    <!-- <a href="#screens">
      <button class="continue-fab mdl-button mdl-button--colored mdl-js-button mdl-button--fab mdl-js-ripple-effect" data-upgraded="MaterialButton,MaterialRipple">
        <i class="material-icons">expand_more</i>
        <span class="mdl-button__ripple-container">
          <span class="mdl-ripple is-animating" style="width: 160.392px; height: 160.392px; transform: translate(-50%, -50%) translate(24px, 24px);"></span>
        </span>
      </button>
    </a> -->
  </div>
</div>

<div class="page-content">

  <a name="screens"></a>
  <div class="content mdl-grid">

    <% MotherListing.all.each do |ml| %>
      <div class="mdl-cell mdl-cell--6-col-tablet mdl-cell--12-col-phone mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title">
          <%= image_tag "mom1.jpg", :style => "max-height: 80px" %>
          <h2 class="mdl-card__title-text"><%= "#{ml.first_name} #{ml.last_name}" %></h2>
        </div>
        <div class="mdl-card__supporting-text">
          <%= ml.description %>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
            <%= link_to "Check this one out!", mother_listings_path + "/#{ml.id}" %>
          </a>
        </div>
        <div class="mdl-card__menu">
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">X</i>
          </button>
        </div>
      </div>
    <% end %>

  </div>

</div>